### ISSUE TITLE
add scp or SFTP store

### ISSUE THREAD

**Issue by bmabey** [bmabey/provenance#20]
@scizo @mmb90   this is the work (on the scp-store branch) I had done on this https://github.com/bmabey/provenance/commit/eaa4ce17af9617adb8c97058cfe25b7289c4d9ce

I never got to the point of testing it.

Also, I would say that if we do merge this in we should introduce a `provenance[sftp]` subpackage that lists `paramiko` library as a dep.

**Comment by mmb90** [comment]
see #22

**Comment by mmb90** [comment]
Are #22, #27, and #28 sufficient to close this?
