### ISSUE TITLE
pyhton 2.7 compat

### ISSUE THREAD

**Issue by bmabey** [bmabey/provenance#32]
I think the project is pretty close to being compatible with python 2.7. I think we have one function with required keyword syntax (which is python 3.x only) but we could probably change that. We should add support and add python 2 to travis CI.

**Comment by dmaljovec** [comment]
I'd argue for closing this issue given that [death is knocking on legacy Python's door](https://pythonclock.org/).

**Comment by bmabey** [comment]
agreed, we won't do this.
