### ISSUE TITLE
Remove logging configuration from alembic migrations

### ISSUE THREAD

**Issue by jedludlow** [bmabey/provenance#43]
Somewhat related to issue #3.

There is some `logging` configuration that happens associated with `provenance.migrations`, and the way it is currently handled doesn't play very nicely with calling applications. More specifically, the call to `fileConfig` in `provenance.migrations.env` as currently implemented disables any previously instantiated logger instance since it doesn't use [`disable_existing_loggers=False`](https://docs.python.org/3.5/library/logging.config.html#logging.config.fileConfig). Additionally, there is logging configuration for both level and handler happening in `alembic.ini` that probably [should be left to a calling application](https://docs.python.org/3.5/howto/logging.html#configuring-logging-for-a-library) rather than specified in the module.

The net effect is that any logger instance you instantiate before importing `provenance` gets disabled after the import, and the logging configuration stuff messes with the logging level of the root logger, causing unexpected results with logger instances that are instantiated downstream of a `provenance` import. It's not a problem that `alembic` or `sqlalchemy` themselves have loggers in them. Rather, it's that `provenance.migrations` itself is being a bit too aggressive in asserting how it wants the loggers to behave, and that should be left to the calling application rather than asserted inside `provenance` itself. I would suggest removing any logging level or handler configuration.

I'm happy to submit a pull request that implements this if you agree with the concept.

**Comment by bmabey** [comment]
I agree that the logging is too aggressive. The `env` file was autogenerated by `alembic` and is more for use in apps and not libraries. I agree with use that the logging related configuration should be removed. I think that amounts to only removing this line (and related imports): https://github.com/bmabey/provenance/blob/master/provenance/migrations/env.py#L13

Is that what you were proposing?

**Comment by jedludlow** [comment]
Pretty much, yes. You could also remove the associated logging configuration stuff from `alembic.ini` just to be tidy.

**Comment by bmabey** [comment]
Check out this commit ^ and let me know if I missed anything.

**Comment by jedludlow** [comment]
Looks great to me. Thanks!
