### ISSUE TITLE
New `wrapt` version issue 

### ISSUE THREAD

**Issue by jesford** [bmabey/provenance#52]
Versions of `wrapt` >= 1.11.0 lead to a `NotImplementedError` because the `ObjectProxy` does not have the `__copy__()` or `__deepcopy__()` method, as described [here](https://wrapt.readthedocs.io/en/latest/changes.html#version-1-11-0).

I think all that needs to be done for compatibility with newer versions of `wrapt` is to define these methods on the proxy objects in provenance:
- ArtifactProxy
- CallableArtifactProxy

Are there other proxy objects that I am missing?

**Comment by jesford** [comment]
Seems we also need to implement the `__reduce_ex__()` method on the proxy objects. Upon updating my development environment and running the tests I get a lot of the errors below, which trace back to the pickle library.

```
self = <provenance.ArtifactProxy(d81be880106a1349dfea190f7d2a7393) [1, 2, 3] >, protocol = 3

    def __reduce_ex__(self, protocol):
        raise NotImplementedError(
>               'object proxy must define __reduce_ex__()')
E       NotImplementedError: object proxy must define __reduce_ex__()

/anaconda3/envs/provenance-dev/lib/python3.5/site-packages/wrapt/wrappers.py:429: NotImplementedError
```

I'm not too sure where to start on this issue now. I'd love to work on it, but with so many failing tests I'll need some guidance on where to start.

**Comment by bmabey** [comment]
This error is the same type as the one you are trying to fix, the new version of `wrapt` requries that the objects implement `__reduce_ex__` in addition to `copy` (and/or `deepcopy`). `__reduce_ex__` is the new dunder that `pickle` uses. The proxy objects (which you correctly identified) [already implement the older `__reduce__` method](https://github.com/bmabey/provenance/blob/17678103cb170cf62723e5712b3d4cb34057286b/provenance/repos.py#L320-L321). According to [StackOverflow](https://stackoverflow.com/questions/150284/what-is-the-difference-between-reduce-and-reduce-ex) the only thing different with `__reduce_ex__` is that the `pickle` protocol version is passes.

 So, I think to get this to work we need to rename `__reduce__` to `__reduce_ex__` and update the signature to take the `pickle` version. I believe we can safely ignore the `pickle` version for now. (Eventually, we may need to address the `pickle` version but for now let's ignore it.)

**Comment by bmabey** [comment]
I'm not sure why so many tests are failing. I think it is bit rot due to not pinning all of the deps because it all was working then just stopped. :/

**Comment by dmaljovec** [comment]
I gave a go at trying to incorporate the minimal changes suggested in this conversation: see PR #53. Instead of replacing `__reduce__`, I added `__reduce_ex__`, since the SO post mentions using `__reduce__` for backward compatibility. On my local machine it did not seem to change anything in terms of pytest results.
