### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by andersy005** [bmabey/provenance#66]
Is there a timeline on when the next "stable" version of provenance will be available on PyPI? it's been a while since the last release. It would be nice to have the changes on master branch released to PyPI. 

I have a work-in-progress recipe for provenance distribution via `conda-forge`: https://github.com/conda-forge/staged-recipes/pull/11712, and It appears that I need to wait for the next release to be able to move forward with the conda-forge packaging.

**Comment by bmabey** [comment]
Here ya go: https://pypi.org/project/provenance/0.14.0/

Thanks @andersy005 !

**Comment by andersy005** [comment]
Many thanks, @bmabey! I just opened #67 with information about the newly created conda package.
